<script src="<?= URLROOT ?>/js/jquery-3.7.0.min.js"></script>
<script src="<?= URLROOT ?>/js/moment.min.js"></script>
<script src="<?= URLROOT ?>/js/popper.min.js"></script>
<script src="<?= URLROOT ?>/js/bootstrap.min.js"></script>
<script src="<?= URLROOT ?>/js/sweetalert2.js"></script>
<script src="<?= URLROOT ?>/js/daterangepicker.js"></script>
<script src="<?= URLROOT ?>/js/jquery.dataTables.min.js"></script>
<script src="<?= URLROOT ?>/js/dataTables.bootstrap4.min.js"></script>
<script src="<?= URLROOT ?>/text-editor/src/jquery.richtext.min.js"></script>
